### PR TITLE
V2 accommodation

### PR DESCRIPTION
**Pull request by TonyB9000**

### CODE REVIEW

**Comment by TonyB9000** [comment]
Just a heads up if you want to review.  Many changes made.  @tomvothecoder @chengzhuzhang 

I'll merge by Wednesday otherwise.

**Review by chengzhuzhang — COMMENTED** [review]
@TonyB9000 Good progress to accommodate v2!
There are quite some changes in dataset_spec.yaml. Could you briefly talk about what was changed?

**Comment by TonyB9000** [comment]
Regarding the dataset_spec:  With the exception of 1 corrected error, all changes involved sorting of entries in order to better locate duplicates, and to help automate the comparison of branch details when employing the "contracted" dataset_spec format. (Many months ago, I located duplicate variables due to the fact that they were all entered un-sorted, which made it easy to overlook duplicates.)  Also, there are python yaml-writers that will sort dictionary entries, but not list elements, because lists can be formed of "nameless" dictionaries (one would need to canonically serialize each listed dictionary as a string, sort the strings, then convert back to dictionaries.)  I manually sorted the contents of of the case extensions of all 58 E3SM experiments.

**Comment by TonyB9000** [comment]
FWIW:  I testes the new-vs-old dataset_spec by calling "list_e3sm_dsids.py" on each, and checking that the same dataset_ids are generated.  One new one popped up, after making a correction to a very old piControl entry.

**Comment by chengzhuzhang** [comment]
Got it, thank you for clarifying @TonyB9000

**Review by tomvothecoder — APPROVED** [review]
I don't have anything to add from my review

**Comment by TonyB9000** [comment]
OK, thanks Tom!

**Pull request merged**
