### PR TITLE
Replace family of Generate...CMIP6.py setup modules with single modul…

### PR DESCRIPTION
**Pull request by TonyB9000**
…e calling dsm_generate_CMIP6.sh script.  Eliminate system of cwl_workflows formerly configured by the setup modules, and modify datasm state-transition files to reflect the change in flow controls.

**OVERVIEW:**

I created a very short

            datasm/datasm/workflows/jobs/GenerateCMIP6.py (28 lines of code, + 590 lines for dsm_generate_CMIP6.sh)

to replace the “family-of-8” of per-var-type setups (totalling 668 lines of code)

            datasm/datasm/workflows/jobs/GenerateAtm3hrCMIP6.py
            datasm/datasm/workflows/jobs/GenerateAtmDayCMIP6.py
            datasm/datasm/workflows/jobs/GenerateAtmFixedCMIP6.py
            datasm/datasm/workflows/jobs/GenerateAtmMonCMIP6.py
            datasm/datasm/workflows/jobs/GenerateLndMonCMIP6.py
            datasm/datasm/workflows/jobs/GenerateOceanCMIP6.py
            datasm/datasm/workflows/jobs/GenerateOcnFixedCMIP6.py
            datasm/datasm/workflows/jobs/GenerateSeaIceCMIP6.py

            (and probably another 8000+ lines of CWL workflow codes)

The new bash script (datasm/scripts/dsm_generate_CMIP6.sh) fully configures NCO and E2C command-lines for generation of arbitrary CMIP6 datasets, but relies upon several utilities in datasm/tools (installed to the environment "STAGING_TOOLS" area) to operate.  Much of this functional dependency is replicated in datasm/util.py, and could be utilized directly if we convert the bash script to a stand-alone python module.

### CODE REVIEW

**Comment by TonyB9000** [comment]
Comment regarding datasm state changes:  When the datasm system consults its hierarchy of transitions.yaml files to control the launch of subordinate processes, it expects subsequent status-file updates to be limited to those of the relevant transitions graphs.

However, when a significant application is launched and involves own subordinate processes, the desire to record those subordinate status changes (not mitigated by datasm) can result in confused datasm state.  Datasm uses a filesystem "listener" (listener.py) to be alerted to changes in status files it is "listening to", and then attempts to make sense of the status changes.  If thare are not expected messages, the results are not well-defined.  I have a workaround, which involves issuing "COMM:" messages instead of "STAT:" messages, which datasm is designed to ignore.

**Comment by tomvothecoder** [comment]
@TonyB9000 Is this PR ready for review? It is marked as a draft PR.

**Comment by tomvothecoder** [comment]
Also can you point to the exact file(s) that should be reviewed for a quicker turnaround? The diff lists 136 files changed, which are mostly deleted files.

**Comment by TonyB9000** [comment]
@tomvothecoder Certainly:

datasm/datasm.py
	proper use of "exit".
	avoid "split" fail when parsing misregistered status file messages

datasm/resources/derivatives.conf
	Revised field order for clarity

datasm/scripts/dsm_generate_CMIP6.sh
	(146) added support for land/snw (aka "land_ice_mon")

	(314) force only 1-file symlink for fx variables
	(327) fixed missing non-MPAS case due to restructure of conditional expression.
	(384) added "land_ice_mon" datatype switch.

	(436)(444)(502)(520)(529)(561)
	(589) Use "COMM:" tag for non-failure exit status-file updates

datasm/tools/derivatives_conf.sh
	Revised field order for clarity (see above derivatives.conf file)

datasm/util.py
	(392) Revised field order for clarity (see above derivatives.conf file)
	Changed log_message status values

datasm/workflows/__init__.py
	Changed log_message status values
	(142) handle processing of subordinate status file changes that are not datasm "state-changes"
		(This entire state handling should be refactored, eventually.  Datasm jobs engage a file-system "listener" that detects when a status-file is written to, and tries to parse the result to direct future processing.  It is brittle and can get confused when unexpected status-file updates are written by subordinate processes not under the datasm/transitions controls.  Temporarily, I avoid this by issuing "COMM:" instead of "STAT:" messages.)

datasm/workflows/jobs/generateCMIP.py
	This new module replaces 8 previous "per-realm/freq" job-setup modules, and consequently hundreds of cwl_workflow files.

datasm/workflows/postprocess/transitions.yaml
datasm/workflows/transitions.yaml
	These state-transition files are updated to eliminate the unnecessary job-control logic for the 8 job-setup/state modules that were eliminated.

**Review by tomvothecoder — APPROVED** [review]
LGTM. Great job refactoring the codebase. This means CWL workflows are no longer used in `datasm`?

**Comment by TonyB9000** [comment]
@tomvothecoder Yes, datasm no longer calls any cwl workflows.  I think they should be archived somewhere just for forensic needs.

**Comment by TonyB9000** [comment]
@chengzhuzhang I changed this from a "draft PR" to a regular PR.  Let me know if you want to review - otherwise I'll perform the merge.

**Pull request merged**
