### PR TITLE
initial update of map and grid files for v3 model data

### PR DESCRIPTION
**Pull request by TonyB9000**
initial update of map and grid files for v3 model data in staging/resource derivatives.conf

### CODE REVIEW

**Comment by chengzhuzhang** [comment]
@TonyB9000 I'm digging out the slack chat with Charlie: "the short answer is that for v3 post-processing we have standardized on `traave` for all components. There's a longer answer [here](https://acme-climate.atlassian.net/wiki/spaces/DOC/pages/178848194/Recommended+Mapping+Procedures+for+E3SM+Atmosphere+Grids) that I think does not affect your current use case". I think we should use `traave` instead?

**Comment by TonyB9000** [comment]
@chengzhuzhang Yes, I recall that (traave) from a while ago, and probably forgot when updating the "derivatives.conf" file for v3.  I recall there were LOTS of options to choose from among maps - but I don't recall where they are provided.

I note there are no "traave" maps listed in /p/user_pub/e3sm/staging/resource/[maps|grids], which is where our tools look for maps via pointers in the derivatives.conf.   Can you point me to the location where ALL of the mapfiles are listed? (I'll make a note of it in the Info directory.)  I will copy over the "traave" maps and edit the derivatives file.

ASIDE:  If that location is expected to be stable, we should have our tools look there directly, instead of maintaining our private copies.  But when it comes to relocation (e.g. to ANL), the location must remain available.

**Comment by TonyB9000** [comment]
@chengzhuzhang Sorry - I just now saw that on Chrysalis, I did place the "traave" maps in the maps directory

/lcrc/group/e3sm2/DSM/Staging/Resource/maps

and they are listed in the derivatives.conf file.  Beware when you update a repo from different systems . . .

I'll straighten this out.

**Comment by TonyB9000** [comment]
@chengzhuzhang What about the regions/masks files?  They are still "EC" (I assume EC is EarthCube, and ICO are the hexagon refinements for Icosahedron?)

ocean,LR,3_0,MASK,**EC30**to60E2r3_mocBasinsAndTransects20210623.nc
ocean,LR,3_0,REGRID,map_**Ico**swISC30E3r5_to_cmip6_180x360_traave.20240221.nc
sea-ice,LR,3_0,MASK,**EC**30to60E2r3_mocBasinsAndTransects20210623.nc
sea-ice,LR,3_0,REGRID,map_**Ico**swISC30E3r5_to_cmip6_180x360_traave.20240221.nc

**Comment by chengzhuzhang** [comment]
@xylar we are trying to find out the mapping files and region mask files for v3.LR simulations. I think we identified `map_IcoswISC30E3r5_to_cmip6_180x360_traave.20240221.nc` as the proper mapping file, could you point out where to look for the mask files.

**Comment by chengzhuzhang** [comment]
> Also, does "traave for ALL components" mean "atmos", "land", etc? I have yet to add ANY entries for 3_0 atmos, etc.

Yes, According to @czender, we should use `traave` mapping files for all components for post-processing. I think Charlie has added all the files here: https://web.lcrc.anl.gov/public/e3sm/diagnostics/maps/

**Comment by xylar** [comment]
@chengzhuzhang, that's one of the appropriate mapping files (conservative one for fluxes).  You also need a bilinear mapping file for state variables.

**Comment by xylar** [comment]
> could you point out where to look for the mask files

Mask files are in:
```
/lcrc/group/e3sm/public_html/diagnostics/mpas_analysis/region_masks
```
or
https://web.lcrc.anl.gov/public/e3sm/diagnostics/mpas_analysis/region_masks/

You want `IcoswISC30E3r5_mocBasinsAndTransects20210623.nc`.  This is only used for the ocean, not the sea ice.

**Comment by xylar** [comment]
> I assume EC is EarthCube,

EC is for Eddy Closure (required at this coarse resolution, but not a great name...)

> and ICO are the hexagon refinements for Icosahedron?)

`Icos` is, indeed, a subdivided icosahedron.

`wISC` means it is "with ice-shelf cavities"

`E3` is E3SM v3

`r5` is revision 5 of the mesh.

**Comment by xylar** [comment]
> Yes, According to @czender, we should use traave mapping files for all components for post-processing. I think Charlie has added all the files here: https://web.lcrc.anl.gov/public/e3sm/diagnostics/maps/

Interesting.  I wouldn't have thought that a conservative remapping would be a good idea for state variables but I will defer to Charlie on that.

**Comment by czender** [comment]
@xylar and @chengzhuzhang My recommendation of TRAAVE for the map algorithm to use for all components in post-processing is based on two criteria: 1. The algorithm should be the same or as close as possible to those used with the online model as shown in the "map-matrix" [here](https://acme-climate.atlassian.net/wiki/spaces/DOC/pages/178848194/Recommended+Mapping+Procedures+for+E3SM+Atmosphere+Grids). (I just noticed that the matrix changed significantly on May 10!). 2. Make it possible to regrid an entire dataset (with flux and state variables) in a single pass, i.e., with one mapfile. TRFV2+CAAS does not seem to be a viable option for post-processing because the CAAS changes every timestep, and many data files contain multiple timesteps. So I recommend TRAAVE instead of TRFV2+CAAS for those fields in post-processing. So the two criteria lead to using TRAAVE (with local-mean renormalization) for all component pairs in post-processing. @xylar is right that now the online model atm->ocn state variables use TRBILIN. However, in post-processing the destination grid is usually rectangular, and together with the "requirement" (which could be relaxed) that one map-file be used for all variables in a datafile, that leads to TRAAVE as the best choice because then all the flux fields are conserved and all the fields are monotonic, full stop. Happy to discuss further.

**Comment by chengzhuzhang** [comment]
@czender For post-processing for data publication (and most atmospheric analyses), we have been using (esmf)aave mapping algorithm regardless of state or fluxes fileds for mapping model output to  i.e. 180x360 cmip grids. (from fine-to-coarse). I was assuming using a same map algorithm (traave) for the same post-processing purpose for v3 is acceptable. Thank you for the insights and clarification.

**Comment by xylar** [comment]
When going from fine to coarse, traave (or the old esmf aave) will be okay.  But The Icos (and old EC) mesh is about the same resolution as 180x360 so I would expect that the results will be noisy for state variables.  I wasn't aware that aave was being used for E3SM v3 state variables.  I thought when we created e3sm_to_cmip that we had different mapping files for state and flux variables and that was part of the validation exercise.  But it was a long time ago and I could be misremembering.  If there is not a distinction between flux and state variables in the workflow, traave is definitely the right map to use as a default.

**Comment by czender** [comment]
@xylar Your comment about noisiness is true. As you know the recommended algorithm for state variables when src and dst meshes are comparable resolution is TRBILIN or TRINTBILIN to prevent such noisiness, and those methods are indeed used in the online model. I explained the rationale for the choices for v3 postprocessing algorithms so it's clear to everyone that the ability to use a single algorithm/mapfile to post-process all variables is an important criteria. The same rationale applied to v2, and led to the choice of ESMFAAVE as @chengzhuzhang notes. The rationale for not using BILIN in post-processing is mainly to avoid the complexity of needing to postprocess with multiple mapfiles for an ever-changing cast of variables. However, IMHO, this should not preclude discussions of whether we want to go down that path, perhaps for a well-defined subset of state variables, or for certain src/dst grid resolutions.

**Comment by xylar** [comment]
Okay, I must have missed when that decision was made but I'll let it be.

**Comment by TonyB9000** [comment]
@xylar "I wasn't aware that aave was being used for E3SM v3 state variables.".  I don't think it has been, except in some preliminary testing.  No significant v3 data has been processed as yet.  I think Jill meant we were anticipating it.

**Comment by TonyB9000** [comment]
@xylar That sounds accurate.  For specific, I have endeavored to maintain a table of maps and grids applied in our CMIP6 generation (currently in flux - I need to update for 3_0 atmos, etc).  The selection is "keyed" off of realm, resolution, and model-version.  Perhaps I need more criteria?:

```
atmos,0_25deg_atm_18-6km_ocean,1_0,REGRID,map_ne120np4_to_cmip6_720x1440_aave.20181001.nc
atmos,1deg_atm_60-30km_ocean,1_0_LE,REGRID,map_ne30np4_to_cmip6_180x360_aave.20181001.nc
atmos,1deg_atm_60-30km_ocean,1_0,REGRID,map_ne30np4_to_cmip6_180x360_aave.20181001.nc
atmos,HR,2_0,REGRID,map_ne120pg2_to_cmip6_720x1440_aave.20200201.nc
atmos,LR,2_0_LE,REGRID,map_ne30pg2_to_cmip6_180x360_aave.20200201.nc
atmos,LR,2_0,REGRID,map_ne30pg2_to_cmip6_180x360_aave.20200201.nc
atmos,LR,2_1,REGRID,map_ne30pg2_to_cmip6_180x360_aave.20200201.nc
atmos,LR-NARRM,2_0_NARRM,REGRID,map_northamericax4v1pg2_to_cmip6_180x360_aave.20200401.nc
land,0_25deg_atm_18-6km_ocean,1_0,REGRID,map_ne120np4_to_cmip6_720x1440_aave.20181001.nc
land,1deg_atm_60-30km_ocean,1_0_LE,REGRID,map_ne30np4_to_cmip6_180x360_aave.20181001.nc
land,1deg_atm_60-30km_ocean,1_0,REGRID,map_ne30np4_to_cmip6_180x360_aave.20181001.nc
land,HR,2_0,REGRID,map_ne120pg2_to_cmip6_720x1440_aave.20200201.nc
land,LR,2_0_LE,REGRID,map_ne30pg2_to_cmip6_180x360_aave.20200201.nc
land,LR,2_0,REGRID,map_ne30pg2_to_cmip6_180x360_aave.20200201.nc
land,LR,2_1,REGRID,map_ne30pg2_to_cmip6_180x360_aave.20200201.nc
land,LR-NARRM,2_0_NARRM,REGRID,map_northamericax4v1pg2_to_cmip6_180x360_aave.20200401.nc
ocean,1deg_atm_60-30km_ocean,1_0_LE,MASK,oEC60to30v3_Atlantic_region_and_southern_transect.nc
ocean,1deg_atm_60-30km_ocean,1_0_LE,REGRID,map_oEC60to30v3_to_cmip6_180x360_aave.20181001.nc
ocean,1deg_atm_60-30km_ocean,1_0,MASK,oEC60to30v3_Atlantic_region_and_southern_transect.nc
ocean,1deg_atm_60-30km_ocean,1_0,REGRID,map_oEC60to30v3_to_cmip6_180x360_aave.20181001.nc
ocean,LR,2_0_LE,MASK,EC30to60E2r2_mocBasinsAndTransects20210623.nc
ocean,LR,2_0_LE,REGRID,map_EC30to60E2r2_to_cmip6_180x360_aave.20220301.nc
ocean,LR,2_0,MASK,EC30to60E2r2_mocBasinsAndTransects20210623.nc
ocean,LR,2_0,REGRID,map_EC30to60E2r2_to_cmip6_180x360_aave.20220301.nc
ocean,LR,2_1,MASK,EC30to60E2r2_mocBasinsAndTransects20210623.nc
ocean,LR,2_1,REGRID,map_EC30to60E2r2_to_cmip6_180x360_aave.20220301.nc
ocean,LR,3_0,MASK,EC30to60E2r3_mocBasinsAndTransects20210623.nc
ocean,LR,3_0,REGRID,map_IcoswISC30E3r5_to_cmip6_180x360_traave.20240221.nc
ocean,LR-NARRM,2_0_NARRM,MASK,WC14to60E2r5_mocBasinsAndTransects20210623.nc
ocean,LR-NARRM,2_0_NARRM,REGRID,map_WC14to60E2r5_to_cmip6_180x360_aave.20230313.nc
sea-ice,1deg_atm_60-30km_ocean,1_0_LE,MASK,oEC60to30v3_Atlantic_region_and_southern_transect.nc
sea-ice,1deg_atm_60-30km_ocean,1_0_LE,REGRID,map_oEC60to30v3_to_cmip6_180x360_aave.20181001.nc
sea-ice,1deg_atm_60-30km_ocean,1_0,MASK,oEC60to30v3_Atlantic_region_and_southern_transect.nc
sea-ice,1deg_atm_60-30km_ocean,1_0,REGRID,map_oEC60to30v3_to_cmip6_180x360_aave.20181001.nc
sea-ice,LR,2_0_LE,MASK,EC30to60E2r2_mocBasinsAndTransects20210623.nc
sea-ice,LR,2_0_LE,REGRID,map_EC30to60E2r2_to_cmip6_180x360_aave.20220301.nc
sea-ice,LR,2_0,MASK,EC30to60E2r2_mocBasinsAndTransects20210623.nc
sea-ice,LR,2_0,REGRID,map_EC30to60E2r2_to_cmip6_180x360_aave.20220301.nc
sea-ice,LR,2_1,MASK,EC30to60E2r2_mocBasinsAndTransects20210623.nc
sea-ice,LR,2_1,REGRID,map_EC30to60E2r2_to_cmip6_180x360_aave.20220301.nc
sea-ice,LR,3_0,MASK,EC30to60E2r3_mocBasinsAndTransects20210623.nc
sea-ice,LR,3_0,REGRID,map_IcoswISC30E3r5_to_cmip6_180x360_traave.20240221.nc
sea-ice,LR-NARRM,2_0_NARRM,MASK,WC14to60E2r5_mocBasinsAndTransects20210623.nc
sea-ice,LR-NARRM,2_0_NARRM,REGRID,map_WC14to60E2r5_to_cmip6_180x360_aave.20230313.nc
```

**Comment by xylar** [comment]
It sounds like that may have been why you all decided not to try to have different maps for different fields.  While that would lead to less noisy results for some fields, it would mean you would have another entry (flux vs. state) in your table for each configuration you currently have.

**Comment by TonyB9000** [comment]
@xylar It would not bother me to add it, if it helps.  But it is critical to have this information accessible in a table for process automation.  I am given (via updates to our "dataset_spec", model-version, experiment, resolution, and then realm-by-realm lists of native and CMIP6 variables, from which to produce derivative datasets.  "flux vs state" is not readily accessible in the spec.  If it exists in the file metadata, I was never informed to look for it (and in any case, it should be an externally-defined relationship - I would think.)

**Comment by xylar** [comment]
@TonyB9000, I think we have to let this be.  I think we (the E3SM team) would have to maintain a table of whether each variable is a state or a flux variable.  Domain scientists will know whether each variable is a state or flux field and I would have hoped that CMOR would provide this information (because it isn't model specific) but that doesn't seem to be the case.  It seems like you all haven't been able to get enough engagement from domain scientists to help maintain a table of this kind, so it seems like the fallback solution has been to do conservative interpolation for all variables.  Since I don't have time to help fix this, I think we just stick with that approach.

**Comment by TonyB9000** [comment]
@xylar Thank you for looking into this.  I suppose maintaining such a table locally (E3SM) would be an alternative, updated automatically by examining the metadata for each variable when a new archive arrives. (A simple step, assuming even the means of making the determination is uniform).  Perhaps that is overkill.  But it is good to understand the situation.  I am ignorant regarding the nature of the noise introduced, or resolution lost, by these choices of maps.

**Comment by TonyB9000** [comment]
@chengzhuzhang Given the above discussion, I am still challenged to identify precisely which mapfiles, grids. masks will be applied to CMIP dataset generation for v3 data, for each realm.

`/public/e3sm/diagnostics/maps` lists 5 "traave" entries:

```
map_IcoswISC30E3r5_to_cmip6_180x360_traave.20240221.nc
map_IcosXISC30E3r7_to_cmip6_180x360_traave.20240314.nc
map_ne120pg2_to_cmip6_180x360_traave.20240401.nc
map_ne30pg2_to_cmip6_180x360_traave.20231201.nc
map_r05_to_cmip6_180x360_traave.20231110.nc
```

For "LR" resolution (and non-MPAS), I will guess that `map_ne30pg2_to_cmip6_180x360_traave.20231201.nc` is appropriate.

The table entries I had (somehow) prepared for v3 ocean and sea-ice were these:

```
ocean,LR,3_0,MASK,EC30to60E2r3_mocBasinsAndTransects20210623.nc
ocean,LR,3_0,REGRID,map_IcoswISC30E3r5_to_cmip6_180x360_traave.20240221.nc
sea-ice,LR,3_0,MASK,EC30to60E2r3_mocBasinsAndTransects20210623.nc
sea-ice,LR,3_0,REGRID,map_IcoswISC30E3r5_to_cmip6_180x360_traave.20240221.nc
```

This may have been premature.

I note that `/public/e3sm/diagnostics/mpas_analysis/maps`` lists roughly 350 maps, and I have no idea which, if any, are appropriate for MPAS CMIP6 generation.  Likewise, almost 250 region_masks exist.

@xylar wrote (regarding masks):

`You want IcoswISC30E3r5_mocBasinsAndTransects20210623.nc. This is only used for the ocean, not the sea ice.`

So, at least one of my 4 table entries looks OK.  But for sea-ice ... ?

(BTW, https://web.lcrc.anl.gov/public/e3sm/diagnostics/e3sm_to_cmip_data/ lists maps and grids and other materials that are quite out-of-date.  Who should maintain this material - and don't all look at me. ;) )

**Comment by chengzhuzhang** [comment]
@TonyB9000 I think what Xylar meant is that sea-ice doesn't need a mask file,i.e. IcoswISC30E3r5_mocBasinsAndTransects20210623.nc

 I think only the variable msftmz: Ocean Meridional Overturning Mass Streamfunction needs such a mask file. 

Could you also take care updating data here: https://web.lcrc.anl.gov/public/e3sm/diagnostics/e3sm_to_cmip_data/  the local path is /lcrc/group/e3sm/public_html/diagnostics/e3sm_to_cmip_data/ (yes, I'm looking at you again)... then there is a `mache` tool to keep all supported machines in sync (

**Comment by TonyB9000** [comment]
@chengzhuzhang OK,  I will eliminate the `"sea-ice,*,*,MASK"` entries from the derivatives.conf file.  I thought it might be needed for any MPAS processing.

I will employ `map_ne30pg2_to_cmip6_180x360_traave.20231201.nc` for non-MPAS (v3) regridding.

I'll log into chrysalis and see what I can do to update the `e3sm_to_cmip_data` content.

**Comment by chengzhuzhang** [comment]
Thank you @TonyB9000

**Comment by czender** [comment]
@TonyB9000 Just making sure you know that the correct map LR for v3 ELM is `map_r05_to_cmip6_180x360_traave.20231110.nc`

**Comment by TonyB9000** [comment]
@czender Thank you Charlie!  No, I did not know that and had the wrong v3 ELM map!   Previously (v2), we had employed the same map for both EAM and ELM (map_ne30pg2_to_cmip6_180x360_aave.20200201.nc).  So now:

```
v3 LR EAM: map_ne30pg2_to_cmip6_180x360_traave.20231201.nc
v3 LR ELM: map_r05_to_cmip6_180x360_traave.20231110.nc
```
If you please, how should I have made this determination?  I sought the page:

https://acme-climate.atlassian.net/wiki/spaces/DOC/pages/178848194/Recommended+Mapping+Procedures+for+E3SM+Atmosphere+Grids#RecommendedMappingProceduresforE3SMAtmosphereGrids-E3SMv3.LRMappingtable

but honestly cannot make sense of it.

**Comment by czender** [comment]
Aloha @TonyB9000. I do not have one-size-fits-all-forever answer to your question. E3SM components evolve and adopt new grids, sometimes, as versions change. One of my jobs is to make sure post-processing support works so I track grids and mapfiles carefully. Just ask me (or @xylar for MPAS) if you're unsure. You can always check that a mapfile is correct by attempting to regrid data with it. Another check is that (the product of) the horizontal dimensions in a source data file equals the sizes of the `n_a` dimension in the associated mapfile. The regridder will fail and spit out these numbers as an ERROR message if you use the wrong mapfile.
I personally do not use the file `IcoswISC30E3r5_mocBasinsAndTransects20210623.nc` but it's definitely for the v3 ocean model so I guess that  another tool like `zppy` uses it. However, these lines
```
ocean,3_0,LR,REGRID,map_ne30pg2_to_cmip6_180x360_traave.20231201.nc <-- Ocean is not on ne30pg2
sea-ice,3_0,LR,REGRID,map_ECwISC30to60E3r2_to_cmip6_180x360_aave.20230901.nc <- This looks like a mapfile for an unreleased, early version of v3?
```
appear to be incorrect because the mapfile for regridding raw ocean data to 180x360 is the same as that for the sea-ice model (i.e., ocean and sea-ice models run on the same grid), and v3 LR simulations for both ocean and ice should use `map_IcoswISC30E3r5_to_cmip6_180x360_traave.20231201.nc`.
And yes, AFAIK, MOSART and ELM are on the same grid and should use the same mapping file.

**Comment by TonyB9000** [comment]
@czender Thank you so much for clarifying.  Probably naive of me to think that CMIP would demand a particular regridding and that E3SM would know what that is.  Too much freedom! :)  Until I have v3 data in hand with which to experiment, I'll just have to settle for close-enough and then wait.  Enjoy!

**Pull request merged**
