### PR TITLE
upped e2c to 1.8.2

### PR DESCRIPTION
**Pull request by TonyB9000**
Note that I left nco at 5.0.6, no idea if I should up to 5.0.7

### CODE REVIEW

**Comment by tomvothecoder** [comment]
Once https://github.com/conda-forge/e3sm_to_cmip-feedstock/pull/20 is merged and 1.8.2 is released on `conda-forge`, you can bump the version of e2c to 1.8.2 in this PR. You can also bump nco to 5.0.7 here.

Afterwards, make sure to test the environment build using these instructions before this PR can be merged: https://github.com/E3SM-Project/datasm/blob/master/docs/getting_started.md#how-to-update-dependencies

**Comment by tomvothecoder** [comment]
> The only reference to testing is given in item (4), which says:

This is the step for testing, but also updating (if you are another developer who needs the new dependencies in the env).

> 6. Update existing conda envs with yml files:

# -n <NAME_OF_ENV> must be specified if you used a custom env name instead of the default name found in the yml file.
conda env update --f conda-env/<NAME_OF_YML>.yml

It should also be listed as step 4, then subsequent steps should be incremented by 1.

**Comment by TonyB9000** [comment]
PR resumed. ;)

**Review by tomvothecoder — APPROVED** [review]
If your the environment builds, it is good to go

**Comment by TonyB9000** [comment]
Done.

**Pull request merged**
